// apps/fx-angular-app/src/app/components/api-key-preferences/api-key-preferences.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder } from '@angular/forms';
import { MatDialogRef } from '@angular/material/dialog';
import {
  PERSONAL_KEY,
  API_SETTINGS,
  PERSONAL_KEY_PREF,
  NUM_DAYS_TO_PROMPT,
  PROMPT_PREF
} from '@fx/ui-core-data';
import { APP_TITLE } from '../../shared';
import { DEFAULT_API_KEY } from '@fx/ui-core-data';
import moment from 'moment';

@Component({
  selector: 'fx-api-key-preferences',
  templateUrl: './api-key-preferences.component.html',
  styleUrls: ['./api-key-preferences.component.css']
})
export class ApiKeyPreferencesComponent implements OnInit {
  title = APP_TITLE;

  apiKeyPrefForm = this.fb.group({
    personalKeyPref: PERSONAL_KEY_PREF.defaultValue,
    personalKey: PERSONAL_KEY.defaultValue,
    promptPref: PROMPT_PREF.defaultValue,
    numDaysToPrompt: NUM_DAYS_TO_PROMPT.defaultValue
  });

  personalKeyPref = {
    id: PERSONAL_KEY_PREF.id,
    label: PERSONAL_KEY_PREF.label,
    options: PERSONAL_KEY_PREF.options
  };
  personalKey = {
    id: PERSONAL_KEY.id,
    label: PERSONAL_KEY.label
  };
  promptPref = {
    id: PROMPT_PREF.id,
    label: PROMPT_PREF.label,
    options: PROMPT_PREF.options
  };
  numDaysToPrompt = {
    id: NUM_DAYS_TO_PROMPT.id,
    label: NUM_DAYS_TO_PROMPT.label
  };

  constructor(
    public dialogRef: MatDialogRef<ApiKeyPreferencesComponent>,
    private fb: FormBuilder
  ) {}

  onSubmit() {
    console.log('fired');
    const {
      personalKeyPref,
      personalKey,
      promptPref,
      numDaysToPrompt
    } = this.apiKeyPrefForm.controls;
    let newKey, newNextPrompt;
    if (personalKeyPref.value) {
      newKey = personalKey.value;
      newNextPrompt = new Date().toISOString();
    } else {
      newKey = DEFAULT_API_KEY;
      newNextPrompt =
        promptPref.value === 'never'
          ? promptPref.value
          : moment()
              .add(numDaysToPrompt.value, 'days')
              .toISOString();
    }
    API_SETTINGS.key = localStorage.ALPHA_VANTAGE_API_KEY = newKey;
    API_SETTINGS.nextPrompt = localStorage.ALPHA_VANTAGE_API_KEY_NEXT_PROMPT = newNextPrompt;
    this.dialogRef.close();
  }

  onNoClick(): void {
    this.dialogRef.close();
  }

  ngOnInit(): void {}
}

<h1 mat-dialog-title>Api Key Preferences</h1>
<form [formGroup]="apiKeyPrefForm" novalidate (ngSubmit)="onSubmit()">
  <mat-dialog-content>
    <p>
      To retrieve exchange rates, you are currently using a default Alpha
      Vantage API key that is limited to 5 requests per minute, 500 requests per
      day. It is shared across users.
    </p>
    <p>
      You can generate a free a personal key
      <a href="https://www.alphavantage.co/support/#api-key" target="_blank"
        >here</a
      >
      and enter below to use with <strong>{{ title }}</strong> on this browser.
    </p>
    <div>
      <mat-label>{{ personalKeyPref.label }}</mat-label>
      <div class="formRow">
        <mat-radio-group formControlName="personalKeyPref">
          <mat-radio-button
            *ngFor="let option of personalKeyPref.options"
            [value]="option.value"
            class="formRowItem"
          >
            {{ option.label }}
          </mat-radio-button>
        </mat-radio-group>
        <mat-form-field
          class="formRowItem"
          *ngIf="apiKeyPrefForm.controls.personalKeyPref.value"
        >
          <mat-label>{{ personalKey.label }}</mat-label>
          <input
            [name]="personalKey.id"
            matInput
            formControlName="personalKey"
          />
        </mat-form-field>
      </div>
    </div>
    <div *ngIf="!apiKeyPrefForm.controls.personalKeyPref.value">
      <mat-label>{{ promptPref.label }}</mat-label>
      <div class="formRow">
        <mat-radio-group formControlName="promptPref">
          <mat-radio-button
            *ngFor="let option of promptPref.options"
            [value]="option.value"
            class="formRowItem"
          >
            {{ option.label }}
          </mat-radio-button>
        </mat-radio-group>
        <mat-form-field
          class="formRowItem"
          *ngIf="apiKeyPrefForm.controls.promptPref.value === 'after'"
        >
          <mat-label>{{ numDaysToPrompt.label }}</mat-label>
          <input matInput type="number" formControlName="numDaysToPrompt" />
        </mat-form-field>
      </div>
    </div>
  </mat-dialog-content>
  <mat-dialog-actions align="end">
    <button mat-raised-button color="primary" type="submit">
      Save Preferences
    </button></mat-dialog-actions
  >
</form>

// apps/fx-react-app/src/app/components/api-key-preferences/api-key-preferences.tsx
import React, { useState, useCallback, useMemo } from 'react';
import {
  Button,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions
} from '@material-ui/core';
import moment from 'moment';

import { API_SETTINGS, DEFAULT_API_KEY } from '@fx/ui-core-data';
import { PreferencesText } from './preferences-dialog-text';
import { PersonalKeyPreferences } from './personal-key-preferences';
import { SharedKeyPreferences } from './shared-key-preferences';

export const PERSONAL_KEY_PREF = 'personal-key-pref';
export const PROMPT_PREF = 'prompt-pref';
export const NUM_DAYS_TO_PROMPT = 'num-days-to-prompt';
export const PERSONAL_KEY = 'personal-key';

const shouldPrompt = (): boolean =>
  API_SETTINGS.key === DEFAULT_API_KEY &&
  API_SETTINGS.nextPrompt !== 'never' &&
  moment().isAfter(moment(API_SETTINGS.nextPrompt));

export const ApiKeyPreferences = () => {
  console.log(API_SETTINGS.key, API_SETTINGS.nextPrompt);
  const [open, setOpen] = useState(shouldPrompt());
  const [personalKeyPref, setPersonalKeyPref] = useState(true);
  const [personalKey, setPersonalKey] = useState('');
  const [promptPref, setPromptPref] = useState('after');
  const [numDaysToPrompt, setNumDaysToPrompt] = useState(10);

  const promptAfterTimestamp = useMemo(
    () =>
      moment()
        .add(numDaysToPrompt, 'days')
        .toISOString(),
    [numDaysToPrompt]
  );

  const handleChange = useCallback(
    (event: React.ChangeEvent<HTMLInputElement>) => {
      event.stopPropagation();
      const { name: fieldName, value } = event.target;
      switch (fieldName) {
        case PERSONAL_KEY_PREF:
          setPersonalKeyPref(JSON.parse(value));
          break;
        case PROMPT_PREF:
          setPromptPref(value);
          break;
        case NUM_DAYS_TO_PROMPT:
          setNumDaysToPrompt(JSON.parse(value));
          break;
        case PERSONAL_KEY:
          setPersonalKey(value);
          break;
        default:
          throw new Error('Attempting to set unknown API key preference');
      }
    },
    [setPersonalKeyPref, setPromptPref, setNumDaysToPrompt, setPersonalKey]
  );

  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    event.stopPropagation();
    let newKey, newNextPrompt;
    if (personalKeyPref) {
      newKey = personalKey;
      newNextPrompt = new Date().toISOString();
    } else {
      newKey = DEFAULT_API_KEY;
      newNextPrompt =
        promptPref === 'never' ? promptPref : promptAfterTimestamp;
    }
    API_SETTINGS.key = localStorage.ALPHA_VANTAGE_API_KEY = newKey;
    API_SETTINGS.nextPrompt = localStorage.ALPHA_VANTAGE_API_KEY_NEXT_PROMPT = newNextPrompt;
    setOpen(false);
  };

  return (
    <Dialog open={open} onClose={() => setOpen(false)} maxWidth="sm">
      <DialogTitle>API key prefrences</DialogTitle>
      <form onSubmit={handleSubmit}>
        <DialogContent>
          <PreferencesText />
          <PersonalKeyPreferences
            personalKeyPref={personalKeyPref}
            personalKey={personalKey}
            handleChange={handleChange}
          />
          {!personalKeyPref && (
            <SharedKeyPreferences
              promptPref={promptPref}
              handleChange={handleChange}
              numDaysToPrompt={numDaysToPrompt}
            />
          )}
        </DialogContent>
        <DialogActions>
          <Button
            type="submit"
            variant="contained"
            color="primary"
            disabled={personalKeyPref && !personalKey}
          >
            Save Preferences
          </Button>
        </DialogActions>
      </form>
    </Dialog>
  );
};
