// apps/fx-angular-app/src/app/components/historical-rates-chart/historical-rates-chart.component.ts
import { Component, OnInit } from '@angular/core';
import { Chart } from 'angular-highcharts';
import { XrangePointOptionsObject } from 'highcharts';
import { combineLatest } from 'rxjs';
import { map } from 'rxjs/operators';
import {
  baseLineOptions,
  fxEntriesToXpointData,
  lineChartOptions,
  CurrencySymbol,
  historicalChartOptions
} from '@fx/ui-core-data';
import { HistoricalRates } from '../../services/historical-rates/historical-rates.service';
import { CurrencySelectionsService } from '../../services/currency-selections/currency-selections.service';

@Component({
  selector: 'fx-historical-chart',
  templateUrl: './historical-rates-chart.component.html'
})
export class HistoricalRatesChartComponent implements OnInit {
  options = baseLineOptions;

  chart = new Chart(this.options);

  constructor(
    private historicalRatesService: HistoricalRates,
    private currencySelections: CurrencySelectionsService
  ) {}

  private setNewOptions(
    base: CurrencySymbol,
    quote: CurrencySymbol,
    data: XrangePointOptionsObject[]
  ) {
    this.options = lineChartOptions(historicalChartOptions(data, base, quote));
  }

  private setNewChart() {
    this.chart = new Chart(this.options);
  }

  ngOnInit(): void {
    combineLatest([
      this.historicalRatesService.fxEntries.pipe(
        map(values => fxEntriesToXpointData(values))
      ),
      this.currencySelections.base,
      this.currencySelections.quote
    ]).subscribe(([data, base, quote]) => {
      this.setNewOptions(base, quote, data);
      this.setNewChart();
    });
  }
}

<div [chart]="chart"><div>

// apps/fx-react-app/src/app/components/historical-rates-chart/historical-rates-chart.tsx
import React, { useMemo } from 'react';
import { HighchartsWrapper } from '../highcharts-wrapper/highcharts-wrapper';
import {
  historicalChartOptions,
  fxEntriesToXpointData,
  lineChartOptions,
  FxEntries,
  CurrencySymbol
} from '@fx/ui-core-data';

interface HistoricalRatesChartProps {
  historicalRates: FxEntries;
  base: CurrencySymbol;
  quote: CurrencySymbol;
}
export const HistoricalRatesChart = ({
  historicalRates,
  base,
  quote
}: HistoricalRatesChartProps) => {
  const data = useMemo(() => fxEntriesToXpointData(historicalRates), [
    historicalRates
  ]);
  return (
    <HighchartsWrapper
      options={lineChartOptions(historicalChartOptions(data, base, quote))}
    />
  );
};
