// apps/fx-react-app/src/app/components/intraday-rates-grid/intraday-rates-grid.tsx
import React from 'react';
import { AgGridWrapper } from '../ag-grid-wrapper/ag-grid-wrapper';
import {
  intradayRatesGridColumnDefs,
  intradayRatesGridDefaultColDef
} from '../../../../../../libs/shared/src/lib/constants/grids';
import { FxEntries, CurrencySymbol } from '@fx/test';
import {
  rowDataFromFxEntries,
  currencyFormatterFactory,
  utcStringToLocal
} from '../../../../../../libs/shared/src/lib/functions';

interface IntradayRatesGridProps {
  intradayRates: FxEntries;
  quoteCurrency: CurrencySymbol;
}
export const IntradayRatesGrid = ({
  intradayRates,
  quoteCurrency
}: IntradayRatesGridProps) => {
  return (
    <AgGridWrapper
      title="Intraday Rates"
      columnDefs={intradayRatesGridColumnDefs}
      defaultColDef={intradayRatesGridDefaultColDef}
      rowData={rowDataFromFxEntries(
        intradayRates,
        currencyFormatterFactory(quoteCurrency),
        utcStringToLocal
      )}
    />
  );
};

// apps/fx-angular-app/src/app/components/intraday-rates-grid/intraday-rates-grid.component.ts
import { Component, OnInit } from '@angular/core';
import { IntradayRates } from '../../services/intraday-rates/intraday-rates.service';
import { combineLatest } from 'rxjs';
import {
  currencyFormatterFactory,
  utcStringToLocal
} from '../../../../../../libs/shared/src';
import { CurrencySelectionsService } from '../../services/currency-selections/currency-selections.service';
import { rowDataFromFxEntries } from '../../../../../../libs/shared/src/lib/functions';
import {
  intradayRatesGridDefaultColDef,
  intradayRatesGridColumnDefs
} from '../../../../../../libs/shared/src/lib/constants/grids';

@Component({
  selector: 'fx-intraday-grid',
  templateUrl: './intraday-rates-grid.component.html',
  styleUrls: ['./intraday-rates-grid.component.css']
})
export class IntradayRatesGridComponent implements OnInit {
  defaultColDef = intradayRatesGridDefaultColDef;
  columnDefs = intradayRatesGridColumnDefs;
  rowData = [];
  constructor(
    private intradayRatesService: IntradayRates,
    private selectedCurrencyService: CurrencySelectionsService
  ) {}

  ngOnInit(): void {
    combineLatest([
      this.selectedCurrencyService.quote,
      this.intradayRatesService.fxEntries
    ]).subscribe({
      next: ([quote, entries]) => {
        this.rowData = rowDataFromFxEntries(
          entries,
          currencyFormatterFactory(quote),
          utcStringToLocal
        );
      }
    });
  }
}
