// apps/fx-react-app/src/app/components/intraday-rates-chart/intraday-rates-chart.tsx
import React, { useMemo } from 'react';
import { HighchartsWrapper } from '../highcharts-wrapper/highcharts-wrapper';

import {
  CurrencySymbol,
  FxEntries,
  INTRADAY_CHART_NAME,
  fxEntriesToXpointData,
  utcStringToLocal,
  lineChartOptions
} from '@fx/ui-core-data';

interface IntradayRatesChartProps {
  intradayRates: FxEntries;
  base: CurrencySymbol;
  quote: CurrencySymbol;
}
export const IntradayRatesChart = ({
  intradayRates,
  base,
  quote
}: IntradayRatesChartProps) => {
  const data = useMemo(
    () => fxEntriesToXpointData(intradayRates, utcStringToLocal),
    [intradayRates]
  );
  return (
    <HighchartsWrapper
      options={lineChartOptions({
        title: `${base}/${quote}`,
        data,
        name: INTRADAY_CHART_NAME,
        stepFactor: 6
      })}
    />
  );
};

// apps/fx-angular-app/src/app/components/intraday-rates-chart/intraday-rates-chart.component.ts
import { Component, OnInit } from '@angular/core';
import { Chart } from 'angular-highcharts';
import { combineLatest } from 'rxjs';
import { map } from 'rxjs/operators';
import {
  fxEntriesToXpointData,
  baseLineOptions,
  lineChartOptions,
  INTRADAY_CHART_NAME
} from '@fx/ui-core-data';
import { IntradayRates } from '../../services/intraday-rates/intraday-rates.service';
import { CurrencySelectionsService } from '../../services/currency-selections/currency-selections.service';

@Component({
  selector: 'fx-intraday-chart',
  templateUrl: './intraday-rates-chart.component.html'
})
export class IntradayRatesChartComponent implements OnInit {
  options = baseLineOptions;

  chart = new Chart(this.options);

  constructor(
    private intradayRates: IntradayRates,
    private currencySelections: CurrencySelectionsService
  ) {}

  private setNewOptions(base, quote, data) {
    this.options = lineChartOptions({
      name: INTRADAY_CHART_NAME,
      title: `${base}/${quote}`,
      data,
      stepFactor: 6
    });
  }

  private setNewChart() {
    this.chart = new Chart(this.options);
  }

  ngOnInit(): void {
    combineLatest([
      this.intradayRates.fxEntries.pipe(
        map(values => fxEntriesToXpointData(values))
      ),
      this.currencySelections.base,
      this.currencySelections.quote
    ]).subscribe(([data, base, quote]) => {
      this.setNewOptions(base, quote, data);
      this.setNewChart();
    });
  }
}
