// apps/fx-angular-app/src/app/components/realtime-card/realtime-card.component.ts
import { Component, OnInit } from '@angular/core';
import { LiveRate } from '../../../../../../libs/shared/src';
import { LiveRateService } from '../../services/live-rate/live-rate.service';
import { CurrencySelectionsService } from '../../services/currency-selections/currency-selections.service';
import { combineLatest } from 'rxjs';
import { sample } from 'rxjs/operators';
import { formatLiveRateForView } from '../../../../../../libs/shared/src/lib/functions';

@Component({
  selector: 'fx-realtime-card',
  templateUrl: './realtime-card.component.html',
  styleUrls: ['./realtime-card.component.css']
})
export class LiveRateComponent implements OnInit {
  liveRate: LiveRate<string, string>;
  constructor(
    private service: LiveRateService,
    private currencySelectionService: CurrencySelectionsService
  ) {}

  ngOnInit(): void {
    combineLatest([
      this.service.rate,
      this.currencySelectionService.base,
      this.currencySelectionService.quote
    ])
      .pipe(sample(this.service.rate))
      .subscribe(([rate, base, quote]) => {
        this.liveRate = formatLiveRateForView(rate, base, quote);
      });
  }
}

// apps/fx-react-app/src/app/components/realtime-card/realtime-card.tsx
import React from 'react';
import { FxCard } from '../fx-card/fx-card';
import {
  LiveRate,
  CurrencySymbol
} from '../../../../../../libs/shared/src/lib/types';
import { Moment } from 'moment';
import { formatLiveRateForView } from '../../../../../../libs/shared/src/lib/functions';
import { CurrencyReserves } from '../currency-reserves/currency-reserves';
import { CurrencyExchange } from '../currency-exchange/currency-exchange';

interface RealTimeCardProps {
  liveRate: LiveRate<number, Moment>;
  base: CurrencySymbol;
  quote: CurrencySymbol;
}
export const RealTimeCard = ({ liveRate, base, quote }: RealTimeCardProps) => {
  const { rate, refreshTime } = formatLiveRateForView(liveRate, base, quote);
  return (
    <FxCard title={rate} subtitle={`Live rate @ ${refreshTime}`}>
      <CurrencyReserves base={base} quote={quote} />
      <CurrencyExchange base={base} quote={quote} rate={liveRate.rate} />
    </FxCard>
  );
};
