// apps/fx-react-app/src/app/components/transactions-grid/transactions-grid.tsx
import React, { useState, useEffect } from 'react';
import Card from '@material-ui/core/Card';
import CardHeader from '@material-ui/core/CardHeader';
import { useAsync } from 'react-use';
import { CardContent } from '@material-ui/core';
import { ColDef } from 'ag-grid-community';
import { AgGridReact } from 'ag-grid-react';
import 'ag-grid-community/dist/styles/ag-grid.css';
import 'ag-grid-community/dist/styles/ag-theme-balham.css';
import { FxTransactionDbClientInstance } from '../../transactionDbClient';
import {
  Transaction,
  transactionsToGridProjection
} from '../../../../../../libs/shared/src';

const defaultColDef: ColDef = {
  sortable: true,
  cellClass: 'align-right',
  headerClass: 'align-right',
  width: 120
};

const columnDefs: ColDef[] = [
  {
    headerName: 'Timestamp',
    field: 'timestamp',
    width: 200
  },
  {
    headerName: 'Pay',
    field: 'payAmount'
  },
  {
    headerName: 'Receive',
    field: 'receiveAmount'
  },
  {
    headerName: 'Pay Balance',
    field: 'payCurrencyBalance'
  },
  {
    headerName: 'Receive Balance',
    field: 'receiveCurrencyBalance'
  }
];

export const TransactionsGrid = () => {
  const [rowData, setRowData] = useState<Transaction<string>[]>([]);
  const transactions = useAsync(FxTransactionDbClientInstance.getTransactions);

  useEffect(() => {
    const { value: resolved } = transactions;
    if (resolved) {
      setRowData(resolved.reverse().map(transactionsToGridProjection));
    }
  }, [transactions.value]);

  return (
    <Card>
      <CardHeader title="Transactions"></CardHeader>
      <CardContent>
        <div
          className="ag-theme-balham"
          style={{ height: '600px', maxWidth: '1400px' }}
        >
          <AgGridReact
            defaultColDef={defaultColDef}
            columnDefs={columnDefs}
            rowData={rowData}
          />
        </div>
      </CardContent>
    </Card>
  );
};

// apps/fx-angular-app/src/app/components/transactions-grid/transactions-grid.component.ts
import { Component, OnInit } from '@angular/core';
import { ColDef } from 'ag-grid-community';
import { TransactionsService } from '../../services/transactions/transactions.service';
import { currencyFormatterFactory } from '../../shared/functions';
import { Transaction } from '../../shared/types';

@Component({
  selector: 'fx-transactions-grid',
  templateUrl: './transactions-grid.component.html',
  styleUrls: ['./transactions-grid.component.css']
})
export class TransactionsGridComponent implements OnInit {
  defaultColDef: ColDef = {
    sortable: true,
    cellClass: 'align-right',
    headerClass: 'align-right',
    width: 120
  };
  columnDefs: ColDef[] = [
    {
      headerName: 'Timestamp',
      field: 'timestamp',
      width: 200
    },
    {
      headerName: 'Pay',
      field: 'payAmount'
    },
    {
      headerName: 'Receive',
      field: 'receiveAmount'
    },
    {
      headerName: 'Pay Balance',
      field: 'payCurrencyBalance'
    },
    {
      headerName: 'Receive Balance',
      field: 'receiveCurrencyBalance'
    }
  ];

  rowData: Transaction<string>[] = [];

  constructor(private transactionService: TransactionsService) {}

  ngOnInit(): void {
    this.transactionService.transactions.subscribe(transactions => {
      this.rowData = transactions
        .reverse()
        .map(
          ({
            payAmount,
            payCurrency,
            receiveAmount,
            receiveCurrency,
            payCurrencyBalance,
            receiveCurrencyBalance,
            timestamp
          }) => {
            const payFormatter = currencyFormatterFactory(payCurrency, 2);
            const receiveFormatter = currencyFormatterFactory(
              receiveCurrency,
              2
            );
            return {
              timestamp,
              payCurrency,
              receiveCurrency,
              payAmount: payFormatter(payAmount),
              receiveAmount: receiveFormatter(receiveAmount),
              payCurrencyBalance: payFormatter(payCurrencyBalance),
              receiveCurrencyBalance: receiveFormatter(receiveCurrencyBalance)
            };
          }
        );
    });
  }
}

<ag-grid-angular
  class="ag-theme-balham fx-grid"
  [rowData]="rowData"
  [columnDefs]="columnDefs"
  [defaultColDef]="defaultColDef"
  style="max-width: 1400px; height: 600px; margin: 0 auto;"
>
</ag-grid-angular>
